### ISSUE TITLE
question: Merge `ClientFlowEvent::AuthenticateAccepted` and `ClientFlowEvent::AuthenticateRejected`?

### ISSUE THREAD

**Issue by duesee** [duesee/imap-flow#142]
Currently, it's possible that we produce non-sensical events, e.g., `AuthenticateAccepted` that has a negative `Status` or `AuthenticateRejected` that has a positive `Status`.

We could merge them to `AuthenticateStatusReceived` and let users figure out what happened using the `Status.kind`.

**Comment by jakoschiko** [comment]
I'm not 100% convinced, but let's do it.

We have a similar problem with other event types like `CommandRejected`, but in this case not all status types are allowed.

**Comment by jakoschiko** [comment]
We could also add something like `StatusNo`, `StatusBad`, `StatusNoOrBad` to `imap_flow::types`, similar to `CommandAuthenticate`, and use them where appropriate. Would be very nice for setter methods like `ServerFlow::idle_reject`. What do you think?

**Comment by jakoschiko** [comment]
These workarounds are quite easy to implement in `imap-flow`. Making the changes in `imap-types` requires more effort  and I'm not sure whether or when you will do it. So IMO let's add more stuff to `imap_flow::types`.

**Comment by duesee** [comment]
Fair enough. Proposal: Let's add to `imap-flow` first and open an issue to reevaluate if we want to merge it into `imap-types` close to some release.
