### ISSUE TITLE
question: Make imap-flow "sans I/O"?

### ISSUE THREAD

**Issue by duesee** [duesee/imap-flow#154]
See https://sans-io.readthedocs.io/ and https://fractalideas.com/blog/sans-io-when-rubber-meets-road/ I very much relate with what is written on the subject.

Examples

* https://github.com/python-hyper/h2/blob/master/examples/plain_sockets/plain_sockets_client.py (Thanks, @epilys)

**Comment by jakoschiko** [comment]
This might solve problems like #98 or #134 (or at least move the responsibility to the user of imap-flow).

**Comment by jakoschiko** [comment]
On the other hand, this might remove our ability to force how the stream is handled, e.g. see #146.
