### ISSUE TITLE
Find better way for consuming AsyncRead + AsyncWrite + Send types

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-flow#18]
- The constructors of ClientFlow and ServerFlow take byte stream. This stream needs to implement AsyncRead + AsyncWrite + Send
- We achieve by using several types, see module imap-flow::stream
- Maybe there is a more lightweight way for achieving this with a smaller API

**Comment by duesee** [comment]
TODO @duesee: Paste DEFLATE / STARTTLS example.

**Comment by duesee** [comment]
This is now outdated.
