### ISSUE TITLE
refactor: Rename `imap-flow`

### ISSUE THREAD

**Issue by duesee** [duesee/imap-flow#199]
Reason: There is already a well-established [ImapFlow](https://imapflow.com/).

Notes:

* Rename `...Flow` types
* Check search engine first... 🙈 
* ...

**Comment by duesee** [comment]
* imap-drive
* imap-auto
* imap-mealy
* imap-state
* imap-meal
* ...

:P

**Comment by duesee** [comment]
Hey @jakoschiko! Did I understand right that you have a rather fleshed out proposal for a rename? :-)

If it's imap-next, I'm sold! Do you feel like making the rename?

**Comment by jakoschiko** [comment]
I like imap-next. Let's first discuss more details. I suggest the following changes:

-  imap-next ← imap-flow
-  `imap_next::State`  ← `imap_flow::Flow`
-  `imap_next::State::next`  ← `imap_flow::Flow::progress`
-  `imap_next::Interrupt`  ← `imap_flow::FlowInterrupt`
-  `imap_next::Io`  ← `imap_flow::FlowIo`
-  `imap_next::client::Client`  ← `imap_flow::client::ClientFlow`
-  `imap_next::client::Client::next`  ← `imap_flow::client::ClientFlow::progress`
-  `imap_next::client::CommandHandle`  ← `imap_flow::client::ClientFlowCommandHandle`
-  `imap_next::client::Options`  ← `imap_flow::client::ClientFlowOptions`
-  `imap_next::client::Error`  ← `imap_flow::client::ClientFlowError`
-  `imap_next::client::Event`  ← `imap_flow::client::ClientFlowEvent`
-  `imap_next::server::Server`  ← `imap_flow::server::ServerFlow`
-  `imap_next::server::Server::next`  ← `imap_flow::server::ServerFlow::progress`
-  `imap_next::server::ResponseHandle`  ← `imap_flow::server::ServerFlowResponseHandle`
-  `imap_next::server::Options`  ← `imap_flow::server::ServerFlowOptions`
-  `imap_next::server::Error`  ← `imap_flow::server::ServerFlowError`
-  `imap_next::server::Event`  ← `imap_flow::server::ServerFlowEvent`

**Comment by duesee** [comment]
Yeeeeees!

**Comment by jakoschiko** [comment]
Maybe even rename `Event` to `Next` for aesthetic reasons. But not sure about that.
