### ISSUE TITLE
Release with CI via git tag

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-flow#282]

**Comment by soywod** [comment]
This may help:

https://github.com/pimalaya/himalaya/blob/6ff37711357ad60e2bf48a866fa6053bc854ff34/.github/workflows/release.yml#L1-L23

Although it uses an old and unmaintained GitHub actions. This one seems to be active: https://github.com/elgohr/Github-Release-Action. I need to refactor mines as well, so I can propose a PR if interested in?

**Comment by jakoschiko** [comment]
[imap-codec already has a workflow for this](https://github.com/duesee/imap-codec/blob/main/.github/workflows/release.yml), I would use it as template to keep both projects consistent. But thanks!
