### ISSUE TITLE
Should we handle `Status::No` in `ClientFlow::maybe_abort_command`?

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-flow#45]

**Comment by duesee** [comment]
From RFC 3501:

> [...] If instead, the server detected an error in the command, it sends a BAD completion response with a tag matching the command (as described below) to reject the command and prevent the client from sending any more of the command.

From RFC 2683:

> The server should send a BAD response to a command that does not end within the server's maximum accepted command length.

I didn't find any hint towards rejecting literals with `No`. I also played with some popular servers and tried to `LOGIN` with too large usernames, and all returned `<tag> BAD ...`. Thus, there *should* be no need to handle `NO` in `maybe_abort_command`.

Still, we should emit a `warn!`ing on anything that is not `BAD` that supposedly is meant to finish our command-in-progress. As we can ensure never to produce duplicate `Tag`s, this would clearly hint to a misbehaving server.

Proposal: We should close this issue and open another one as a reminder to add the warning log.

**Comment by jakoschiko** [comment]
> Proposal: We should close this issue and open another one as a reminder to add the warning log.

Currently we don't do any logging in `imap-flow`. Instead we propagate all events to the user and let them decide what to do. Maybe it would be better to introduce something like `ClientFlowEvent::UnexpectedStatus`.

**Comment by duesee** [comment]
Yeah, maybe. Let's discuss later. I guess it boils down to what exactly we want `imap-flow` to be. There is also https://github.com/duesee/imap-flow/issues/31.
