### ISSUE TITLE
feat: How do we want to do logging?

### ISSUE THREAD

**Issue by duesee** [duesee/imap-flow#74]

**Comment by jakoschiko** [comment]
Opinion:
- imap-proxy should log
- imap-flow and imap-tasks shouldn't log but emit all events with its data to the user

**Comment by duesee** [comment]
Agree, and agree. `log` crate or `tracing` for `imap-{flow,tasks}`. (My love for `tracing` overshadows all objectivity.)

**Comment by jakoschiko** [comment]
I suggest using println :p

**Comment by duesee** [comment]
https://crates.io/crates/println 🤔

**Comment by duesee** [comment]
* Jakob doesn't care if `log` or `tracing`
  * Prefers to only log in `imap-{flow,tasks}` when unavoidable
  * Log generously in `proxy`
* Damian loves tracing
