### ISSUE TITLE
Ensure that no secrets are exposed by `Debug` output

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-flow#90]
If I understand correctly we want to prevent that the `Debug` output of any type contains any secret.

But what about these cases?
- The read and write buffer of `ClientFlow` and `ServerFlow` may contain the bytes of a secret
- The stream inside of `AnyStream` may contain additional buffers and may write them to its `Debug` output
- Error types like `ClientFlowError::MalformedMessage` may contain the bytes of a secret

**Comment by duesee** [comment]
I think we should generally never `Debug`-print buffers. But it's a bit of a tradeoff, because it can be useful for debugging.

`imap-codec` `Debug`-prints secrets during `--debug` builds and uses `[redacted]` in `--release` builds. The types are the same, but the `Debug` impl has a `cfg()`. 

Should we use this for `imap-flow`, too?

**Comment by jakoschiko** [comment]
There is also tracing in `stream.rs` that we might want to disable in release builds.

**Comment by duesee** [comment]
Hm... I'm going through the code base right now and feel that it would be better to first remove all `Debug` implementations and then reintroduce them as needed. Having `#[deny(missing_debug_implementations)]` makes sense for ?imap-codec`. But maybe less so for `imap-flow`. What do you think?

**Comment by jakoschiko** [comment]
IMO `Debug` for `ClientFlow` and `ServerFlow` isn't really necessary, it was never useful for me in the past.

But I'd like to keep `Debug` for all public `*Event`, `*Error`, `*Handle` and `*Options` types. And I'm fine with using `Secret`.

Your PR seems to implement exactly that, perfect, keep going.
